create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  session_id text not null,
  path text not null default '/',
  referrer text default '',
  user_agent_family text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null,
  section text default '',
  path text default '/',
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text default 'Visitor',
  email text default '',
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  spam_check text default '',
  created_at timestamptz not null default now()
);

alter table public.visits enable row level security;
alter table public.events enable row level security;
alter table public.feedback enable row level security;
alter table public.contact_submissions enable row level security;

create policy "service role manages visits" on public.visits for all using (auth.role() = 'service_role');
create policy "service role manages events" on public.events for all using (auth.role() = 'service_role');
create policy "service role manages feedback" on public.feedback for all using (auth.role() = 'service_role');
create policy "service role manages contact submissions" on public.contact_submissions for all using (auth.role() = 'service_role');
